"""empty message

Revision ID: 11339497eca
Revises: 3e5917e360a
Create Date: 2015-05-16 04:59:28.530052

"""

# revision identifiers, used by Alembic.
revision = '11339497eca'
down_revision = '3e5917e360a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('industry_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'business', 'industry', ['industry_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'business', type_='foreignkey')
    op.drop_column('business', 'industry_id')
    ### end Alembic commands ###
