"""empty message

Revision ID: 1218fad123
Revises: 185b30e0a52
Create Date: 2015-05-15 23:23:11.523125

"""

# revision identifiers, used by Alembic.
revision = '1218fad123'
down_revision = '185b30e0a52'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
