"""empty message

Revision ID: 185b30e0a52
Revises: 197d63d2f1d
Create Date: 2015-05-15 22:47:51.660955

"""

# revision identifiers, used by Alembic.
revision = '185b30e0a52'
down_revision = '197d63d2f1d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('login', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('login', 'password_salt',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('login', 'password_salt',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('login', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###
