"""create some indexes on Job table

Revision ID: 1b1f4b2ebf6
Revises: 4fc8f19cb45
Create Date: 2015-07-09 04:21:27.449415

"""

# revision identifiers, used by Alembic.
revision = '1b1f4b2ebf6'
down_revision = '4fc8f19cb45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_job_business_id'), 'job', ['business_id'], unique=False)
    op.create_index(op.f('ix_job_create_date'), 'job', ['create_date'], unique=False)
    op.create_index(op.f('ix_job_employee_id'), 'job', ['employee_id'], unique=False)
    op.create_index(op.f('ix_job_manager_id'), 'job', ['manager_id'], unique=False)
    op.create_index(op.f('ix_job_position_id'), 'job', ['position_id'], unique=False)
    op.create_index(op.f('ix_job_status_id'), 'job', ['status_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_status_id'), table_name='job')
    op.drop_index(op.f('ix_job_position_id'), table_name='job')
    op.drop_index(op.f('ix_job_manager_id'), table_name='job')
    op.drop_index(op.f('ix_job_employee_id'), table_name='job')
    op.drop_index(op.f('ix_job_create_date'), table_name='job')
    op.drop_index(op.f('ix_job_business_id'), table_name='job')
    ### end Alembic commands ###
