"""add nullable unique 'iso_name' column to language table

Revision ID: 1bfd4a4ae2c
Revises: 5a9d75a34db
Create Date: 2015-06-03 08:44:02.232598

"""

# revision identifiers, used by Alembic.
revision = '1bfd4a4ae2c'
down_revision = '5a9d75a34db'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language', sa.Column('iso_name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'language', ['iso_name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'language', type_='unique')
    op.drop_column('language', 'iso_name')
    ### end Alembic commands ###
