"""empty message

Revision ID: 20d3ba48a7
Revises: 41bf2d965d2
Create Date: 2015-06-30 01:00:23.841499

"""

# revision identifiers, used by Alembic.
revision = '20d3ba48a7'
down_revision = '41bf2d965d2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobmatch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_dispatched', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('is_true_match', sa.Boolean(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('fk_jobmatch_employee_id_employee')),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_jobmatch_job_id_job')),
    sa.PrimaryKeyConstraint('employee_id', 'job_id', name=op.f('pk_jobmatch')),
    sa.UniqueConstraint('id', name=op.f('uq_jobmatch_id'))
    )
    op.create_index(op.f('ix_jobmatch_is_dispatched'), 'jobmatch', ['is_dispatched'], unique=False)
    op.create_unique_constraint(op.f('uq_administrator_login_id'), 'administrator', ['login_id'])
    op.drop_constraint('administrator_login_id_key', 'administrator', type_='unique')
    op.create_unique_constraint(op.f('uq_contactinfo_id'), 'contactinfo', ['id'])
    op.drop_constraint('contactinfo_id_key', 'contactinfo', type_='unique')
    op.create_unique_constraint(op.f('uq_employee_human_id'), 'employee', ['human_id'])
    op.create_unique_constraint(op.f('uq_employee_login_id'), 'employee', ['login_id'])
    op.drop_constraint('employee_human_id_unique', 'employee', type_='unique')
    op.drop_constraint('employee_login_id_unique', 'employee', type_='unique')
    op.create_unique_constraint(op.f('uq_human_id'), 'human', ['id'])
    op.drop_constraint('human_id_unique', 'human', type_='unique')
    op.create_unique_constraint(op.f('uq_jobstatus_id'), 'jobstatus', ['id'])
    op.create_unique_constraint(op.f('uq_jobstatus_name'), 'jobstatus', ['name'])
    op.drop_constraint('jobstatus_id_unique', 'jobstatus', type_='unique')
    op.drop_constraint('jobstatus_name_key', 'jobstatus', type_='unique')
    op.create_unique_constraint(op.f('uq_language_iso_name'), 'language', ['iso_name'])
    op.drop_constraint('language_iso_name_key', 'language', type_='unique')
    op.create_unique_constraint(op.f('uq_login_username'), 'login', ['username'])
    op.drop_constraint('login_username_unique', 'login', type_='unique')
    op.create_unique_constraint(op.f('uq_manager_human_id'), 'manager', ['human_id'])
    op.create_unique_constraint(op.f('uq_manager_login_id'), 'manager', ['login_id'])
    op.drop_constraint('manager_human_id_unique', 'manager', type_='unique')
    op.drop_constraint('manager_login_id_unique', 'manager', type_='unique')
    op.create_unique_constraint(op.f('uq_rating_id'), 'rating', ['id'])
    op.drop_constraint('rating_id_key', 'rating', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('rating_id_key', 'rating', ['id'])
    op.drop_constraint(op.f('uq_rating_id'), 'rating', type_='unique')
    op.create_unique_constraint('manager_login_id_unique', 'manager', ['login_id'])
    op.create_unique_constraint('manager_human_id_unique', 'manager', ['human_id'])
    op.drop_constraint(op.f('uq_manager_login_id'), 'manager', type_='unique')
    op.drop_constraint(op.f('uq_manager_human_id'), 'manager', type_='unique')
    op.create_unique_constraint('login_username_unique', 'login', ['username'])
    op.drop_constraint(op.f('uq_login_username'), 'login', type_='unique')
    op.create_unique_constraint('language_iso_name_key', 'language', ['iso_name'])
    op.drop_constraint(op.f('uq_language_iso_name'), 'language', type_='unique')
    op.create_unique_constraint('jobstatus_name_key', 'jobstatus', ['name'])
    op.create_unique_constraint('jobstatus_id_unique', 'jobstatus', ['id'])
    op.drop_constraint(op.f('uq_jobstatus_name'), 'jobstatus', type_='unique')
    op.drop_constraint(op.f('uq_jobstatus_id'), 'jobstatus', type_='unique')
    op.create_unique_constraint('human_id_unique', 'human', ['id'])
    op.drop_constraint(op.f('uq_human_id'), 'human', type_='unique')
    op.create_unique_constraint('employee_login_id_unique', 'employee', ['login_id'])
    op.create_unique_constraint('employee_human_id_unique', 'employee', ['human_id'])
    op.drop_constraint(op.f('uq_employee_login_id'), 'employee', type_='unique')
    op.drop_constraint(op.f('uq_employee_human_id'), 'employee', type_='unique')
    op.create_unique_constraint('contactinfo_id_key', 'contactinfo', ['id'])
    op.drop_constraint(op.f('uq_contactinfo_id'), 'contactinfo', type_='unique')
    op.create_unique_constraint('administrator_login_id_key', 'administrator', ['login_id'])
    op.drop_constraint(op.f('uq_administrator_login_id'), 'administrator', type_='unique')
    op.drop_index(op.f('ix_jobmatch_is_dispatched'), table_name='jobmatch')
    op.drop_table('jobmatch')
    ### end Alembic commands ###
