"""adjust location related columns

* add unique constraints to `fixed_location_id` for Employee and Business, and
    add unique constraint to `current_location_id` for Employee.
* add NOT NULL constraint to `geolocation_id` in FixedLocation.
* adjust foreign key: FixedLocation -> Geolocation

Revision ID: 27128ddffde
Revises: 8a3a274cb4
Create Date: 2015-07-23 09:42:26.938401

"""

# revision identifiers, used by Alembic.
revision = '27128ddffde'
down_revision = '8a3a274cb4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_business_fixed_location_id'), 'business', ['fixed_location_id'])
    op.create_unique_constraint(op.f('uq_employee_current_location_id'), 'employee', ['current_location_id'])
    op.create_unique_constraint(op.f('uq_employee_fixed_location_id'), 'employee', ['fixed_location_id'])
    op.alter_column('fixedlocation', 'geolocation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(op.f('fk_fixedlocation_geolocation_id_geolocation'), 'fixedlocation', 'geolocation', ['geolocation_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_fixedlocation_geolocation_id_geolocation'), 'fixedlocation', type_='foreignkey')
    op.alter_column('fixedlocation', 'geolocation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('uq_employee_fixed_location_id'), 'employee', type_='unique')
    op.drop_constraint(op.f('uq_employee_current_location_id'), 'employee', type_='unique')
    op.drop_constraint(op.f('uq_business_fixed_location_id'), 'business', type_='unique')
    ### end Alembic commands ###
