"""recreate the jobmatch table to get its primary keys right

Revision ID: 2973449045f
Revises: 3044b6d2eec
Create Date: 2015-07-14 01:10:57.558333

"""

# revision identifiers, used by Alembic.
revision = '2973449045f'
down_revision = '3044b6d2eec'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobmatch')
    op.create_table('jobmatch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_dispatched', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('is_true_match', sa.Boolean(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('fk_jobmatch_employee_id_employee')),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_jobmatch_job_id_job')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobmatch')),
    sa.UniqueConstraint('employee_id', 'job_id', name=op.f('uq_jobmatch_employee_id')),
    sa.UniqueConstraint('id', name=op.f('uq_jobmatch_id'))
    )
    op.create_index(op.f('ix_jobmatch_employee_id'), 'jobmatch', ['employee_id'], unique=False)
    op.create_index(op.f('ix_jobmatch_is_dispatched'), 'jobmatch', ['is_dispatched'], unique=False)
    op.create_index(op.f('ix_jobmatch_job_id'), 'jobmatch', ['job_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobmatch_job_id'), table_name='jobmatch')
    op.drop_index(op.f('ix_jobmatch_is_dispatched'), table_name='jobmatch')
    op.drop_index(op.f('ix_jobmatch_employee_id'), table_name='jobmatch')
    op.drop_table('jobmatch')
    op.create_table('jobmatch',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_dispatched', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_true_match', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='fk_jobmatch_employee_id_employee'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name='fk_jobmatch_job_id_job'),
    sa.PrimaryKeyConstraint('employee_id', 'job_id', name='pk_jobmatch'),
    sa.UniqueConstraint('id', name='uq_jobmatch_id')
    )
    ### end Alembic commands ###
