"""create AndroidDevice table to track phones

AndroiDevice instances are tied to a Login.

Revision ID: 2b43c539598
Revises: 49ae29b543
Create Date: 2015-07-14 00:33:32.410030

"""

# revision identifiers, used by Alembic.
revision = '2b43c539598'
down_revision = '49ae29b543'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('androiddevice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.Integer(), nullable=False),
    sa.Column('reg', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['login_id'], ['login.id'], name=op.f('fk_androiddevice_login_id_login'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_androiddevice')),
    sa.UniqueConstraint('reg', name=op.f('uq_androiddevice_reg'))
    )
    op.create_index(op.f('ix_androiddevice_login_id'), 'androiddevice', ['login_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_androiddevice_login_id'), table_name='androiddevice')
    op.drop_table('androiddevice')
    ### end Alembic commands ###
