"""replace start_date to arrival_date and add departure_date column

The start_date of the job is irrelevant since jobs are always of an immediate
nature. The arrival_date and departure_date are when the employee shows up and
leaves.

Revision ID: 2e1051f634f
Revises: 364ea5284fb
Create Date: 2015-06-23 00:00:32.470813

"""

# revision identifiers, used by Alembic.
revision = '2e1051f634f'
down_revision = '364ea5284fb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('arrival_date', sa.DateTime(), nullable=True))
    op.add_column('job', sa.Column('departure_date', sa.DateTime(), nullable=True))
    op.drop_column('job', 'start_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('job', 'departure_date')
    op.drop_column('job', 'arrival_date')
    ### end Alembic commands ###
