"""create indexes on employee_id and job_id in JobMatch

Revision ID: 3044b6d2eec
Revises: 2b43c539598
Create Date: 2015-07-14 00:58:42.677971

"""

# revision identifiers, used by Alembic.
revision = '3044b6d2eec'
down_revision = '2b43c539598'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_jobmatch_employee_id'), 'jobmatch', ['employee_id'], unique=False)
    op.create_index(op.f('ix_jobmatch_job_id'), 'jobmatch', ['job_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobmatch_job_id'), table_name='jobmatch')
    op.drop_index(op.f('ix_jobmatch_employee_id'), table_name='jobmatch')
    ### end Alembic commands ###
