"""empty message

Revision ID: 34467873d03
Revises: 123b14f776f
Create Date: 2015-05-29 17:56:31.947753

"""

# revision identifiers, used by Alembic.
revision = '34467873d03'
down_revision = '123b14f776f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('is_verified', sa.Boolean(),
        nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'is_verified')
    ### end Alembic commands ###
