"""drop useless columns from managerset association table

Revision ID: 364ea5284fb
Revises: 399588cb5d1
Create Date: 2015-06-22 23:07:30.787543

"""

# revision identifiers, used by Alembic.
revision = '364ea5284fb'
down_revision = '399588cb5d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managerset', 'name')
    op.drop_column('managerset', 'level')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managerset', sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('managerset', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
