"""empty message

Revision ID: 3e5917e360a
Revises: 46585e20804
Create Date: 2015-05-16 04:29:02.440679

"""

# revision identifiers, used by Alembic.
revision = '3e5917e360a'
down_revision = '46585e20804'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login', sa.Column('email', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login', 'email')
    ### end Alembic commands ###
