"""add `is_available` column to mark Positions as deleted

We don't ever want to *delete* a Position, for the purposes of keeping
consistent logs, but businesses may stop caring about a certain position and
might want to delete it, so we need to a way to keep track of deleted positions
and not show them to businesses when they list their listings.

Revision ID: 3ee911eb470
Revises: 30d83ea4704
Create Date: 2015-06-25 14:29:30.804304

"""

# revision identifiers, used by Alembic.
revision = '3ee911eb470'
down_revision = '30d83ea4704'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('is_available', sa.Boolean(), server_default='t', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position', 'is_available')
    ### end Alembic commands ###
