"""empty message

Revision ID: 46585e20804
Revises: 2b257be074b
Create Date: 2015-05-16 04:19:25.419223

"""

# revision identifiers, used by Alembic.
revision = '46585e20804'
down_revision = '2b257be074b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('canadian_citizen', sa.Boolean(), nullable=False))
    op.add_column('employee', sa.Column('canadian_work', sa.Boolean(), nullable=False))
    op.add_column('employee', sa.Column('cv_name', sa.String(), nullable=False))
    op.add_column('employee', sa.Column('cv_original_name', sa.String(), nullable=False))
    op.add_column('employee', sa.Column('faculty_id', sa.Integer(), nullable=True))
    op.add_column('employee', sa.Column('graduation_year', sa.String(), nullable=True))
    op.add_column('employee', sa.Column('is_student', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'employee', 'schoolfaculty', ['faculty_id'], ['id'])
    op.add_column('login', sa.Column('phone_number', sa.String(), nullable=False))
    op.add_column('login', sa.Column('postal_code', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login', 'postal_code')
    op.drop_column('login', 'phone_number')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column('employee', 'is_student')
    op.drop_column('employee', 'graduation_year')
    op.drop_column('employee', 'faculty_id')
    op.drop_column('employee', 'cv_original_name')
    op.drop_column('employee', 'cv_name')
    op.drop_column('employee', 'canadian_work')
    op.drop_column('employee', 'canadian_citizen')
    ### end Alembic commands ###
