"""add unique constraint for `Human.id`

Revision ID: 465d8615449
Revises: 14752bd249b
Create Date: 2015-06-22 17:34:55.302884

"""

# revision identifiers, used by Alembic.
revision = '465d8615449'
down_revision = '14752bd249b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('human_id_unique', 'human', ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('human_id_unique', 'human', type_='unique')
    ### end Alembic commands ###
