"""add default duration column for Position

Revision ID: 4d89cd033b5
Revises: 3b3da4064cb
Create Date: 2015-08-04 12:24:02.671824

"""

# revision identifiers, used by Alembic.
revision = '4d89cd033b5'
down_revision = '3b3da4064cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('default_duration', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position', 'default_duration')
    ### end Alembic commands ###
