"""create `jobstatus` table and link to `job` table

The `jobstatus` table is also populated.

Revision ID: 4dc92ef8417
Revises: 4ed7937ef71
Create Date: 2015-06-16 21:30:04.623390

"""

# revision identifiers, used by Alembic.
revision = '4dc92ef8417'
down_revision = '4ed7937ef71'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    jobstatus_table = op.create_table('jobstatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('friendly_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.bulk_insert(jobstatus_table,
            [
                {
                    'name': 'pending',
                    'friendly_name': 'pending',
                },
                {
                    'name': 'submitted',
                    'friendly_name': 'submitted',
                },
                {
                    'name': 'inProgress',
                    'friendly_name': 'in progress',
                },
                {
                    'name': 'cancelled',
                    'friendly_name': 'cancelled',
                },
                {
                    'name': 'completed',
                    'friendly_name': 'completed',
                },
                {
                    'name': 'stale',
                    'friendly_name': 'stale',
                },
                {
                    'name': 'aborted',
                    'friendly_name': 'aborted',
                }
            ]
    )
    op.add_column('job', sa.Column('status_id', sa.Integer(), nullable=False))
    op.create_foreign_key('job_status_id_fkey', 'job', 'jobstatus', ['status_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('job_status_id_fkey', 'job', type_='foreignkey')
    op.drop_column('job', 'status_id')
    op.drop_table('jobstatus')
    ### end Alembic commands ###
