"""add start and end times for jobs, and revise job-rating link

Jobs link to their ratings rather than have ratings link to their job.

Revision ID: 4ed7937ef71
Revises: 1bfd4a4ae2c
Create Date: 2015-06-16 19:33:53.037868

"""

# revision identifiers, used by Alembic.
revision = '4ed7937ef71'
down_revision = '1bfd4a4ae2c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('id', sa.Integer(), unique=True,
        nullable=False, primary_key=True))
    op.drop_constraint('rating_job_id_fkey', 'rating', type_='foreignkey')
    op.drop_column('rating', 'job_id')

    op.add_column('job', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('job', sa.Column('rating_id', sa.Integer(), nullable=False))
    op.add_column('job', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.alter_column('job', 'position_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('job', 'is_available')

    op.create_foreign_key('job_rating_id_fkey', 'job', 'rating', ['rating_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint('job_rating_id_fkey', 'job', type_='foreignkey')
    op.alter_column('job', 'position_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('job', 'start_date')
    op.drop_column('job', 'rating_id')
    op.drop_column('job', 'end_date')
    op.add_column('rating', sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('rating_job_id_fkey', 'rating', 'job', ['job_id'], ['id'])
    op.drop_column('rating', 'id')
    ### end Alembic commands ###
