"""adjust primary key on JobMatch

Revision ID: 5709c85f594
Revises: 3d32478d80f
Create Date: 2015-07-15 19:56:48.618527

"""

# revision identifiers, used by Alembic.
revision = '5709c85f594'
down_revision = '3d32478d80f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_jobmatch_id'), 'jobmatch', ['id'])
    op.drop_index('ix_jobmatch_employee_id', table_name='jobmatch')
    op.drop_index('ix_jobmatch_is_dispatched', table_name='jobmatch')
    op.drop_index('ix_jobmatch_job_id', table_name='jobmatch')
    op.drop_constraint('uq_jobmatch_employee_id', 'jobmatch', type_='unique')
    ### end Alembic commands ###
    op.drop_constraint('pk_jobmatch', 'jobmatch')
    op.create_primary_key('pk_jobmatch', 'jobmatch', ['employee_id', 'job_id'])


def downgrade():
    op.drop_constraint('pk_jobmatch', 'jobmatch')
    op.create_primary_key('pk_jobmatch', 'jobmatch', ['id'])
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_jobmatch_employee_id', 'jobmatch', ['employee_id', 'job_id'])
    op.create_index('ix_jobmatch_job_id', 'jobmatch', ['job_id'], unique=False)
    op.create_index('ix_jobmatch_is_dispatched', 'jobmatch', ['is_dispatched'], unique=False)
    op.create_index('ix_jobmatch_employee_id', 'jobmatch', ['employee_id'], unique=False)
    op.drop_constraint(op.f('uq_jobmatch_id'), 'jobmatch', type_='unique')
    ### end Alembic commands ###
