"""empty message

Revision ID: 5a9d75a34db
Revises: 34467873d03
Create Date: 2015-05-29 17:57:45.711226

"""

# revision identifiers, used by Alembic.
revision = '5a9d75a34db'
down_revision = '34467873d03'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    ### end Alembic commands ###
